version: 0.0
os: linux
files:
  - source: /sample.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: script/install_dependencies
      timeout: 300
      runas: root
    - location: script/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: script/stop_server
      timeout: 300
      runas: root
